apiVersion: v1
kind: Service
metadata:
  name: testaks-2048
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: testaks-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testaks-2048
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testaks-2048
  template:
    metadata:
      labels:
        app: testaks-2048
    spec:
      nodeSelector:
        size: B2s
      containers:
        - name: backend
          image: anjoysutrisna/test-argo-2048:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testaks-2048-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /2048$ http://azure.lordvader.me/2048/ permanent;
  namespace: test
spec:
  ingressClassName: misc-nginx
  rules:
    - host: azure.lordvader.me
      http:
        paths:
          - path: /2048(/|$)(.*)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: testaks-2048
                port:
                  number: 80
